package edu.ijse.ftb.view;

import edu.ijse.ftb.connector.ServerConnector;
import edu.ijse.ftb.controller.BookedController;
import edu.ijse.ftb.controller.CustomerController;
import edu.ijse.ftb.observer.Observer;
import edu.ijse.ftb.observer.Subject;
import java.awt.Color;
import java.awt.Component;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

public class SeatsWindow extends javax.swing.JInternalFrame implements Observer {

    public SeatsWindow swd;

    /**
     * Creates new form SeatsWindow
     */
    public SeatsWindow() {
        initComponents();

        try {
            UnicastRemoteObject.exportObject(this, 0);
            BookedController bc = ServerConnector.getServerConnector().getBookedController();
            Subject s = (Subject) bc;
            s.registerObserver(this);

        } catch (RemoteException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btna1 = new javax.swing.JButton();
        btna2 = new javax.swing.JButton();
        btna3 = new javax.swing.JButton();
        btna4 = new javax.swing.JButton();
        btna5 = new javax.swing.JButton();
        btna6 = new javax.swing.JButton();
        btna7 = new javax.swing.JButton();
        btna8 = new javax.swing.JButton();
        btna9 = new javax.swing.JButton();
        btna10 = new javax.swing.JButton();
        btna12 = new javax.swing.JButton();
        btna13 = new javax.swing.JButton();
        btna14 = new javax.swing.JButton();
        btna15 = new javax.swing.JButton();
        btna16 = new javax.swing.JButton();
        btna17 = new javax.swing.JButton();
        btna18 = new javax.swing.JButton();
        btna19 = new javax.swing.JButton();
        btna20 = new javax.swing.JButton();
        btna22 = new javax.swing.JButton();
        btna23 = new javax.swing.JButton();
        btna24 = new javax.swing.JButton();
        btna25 = new javax.swing.JButton();
        btna26 = new javax.swing.JButton();
        btna27 = new javax.swing.JButton();
        btna28 = new javax.swing.JButton();
        btna29 = new javax.swing.JButton();
        btna30 = new javax.swing.JButton();
        btna21 = new javax.swing.JButton();
        btna11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnb1 = new javax.swing.JButton();
        btnb2 = new javax.swing.JButton();
        btnb3 = new javax.swing.JButton();
        btnb4 = new javax.swing.JButton();
        btnb6 = new javax.swing.JButton();
        btnb7 = new javax.swing.JButton();
        btnb8 = new javax.swing.JButton();
        btnb9 = new javax.swing.JButton();
        btnb10 = new javax.swing.JButton();
        btnb11 = new javax.swing.JButton();
        btnb12 = new javax.swing.JButton();
        btnb13 = new javax.swing.JButton();
        btnb14 = new javax.swing.JButton();
        btnb16 = new javax.swing.JButton();
        btnb17 = new javax.swing.JButton();
        btnb18 = new javax.swing.JButton();
        btnb19 = new javax.swing.JButton();
        btnb20 = new javax.swing.JButton();
        btnb21 = new javax.swing.JButton();
        btnb22 = new javax.swing.JButton();
        btnb23 = new javax.swing.JButton();
        btnb24 = new javax.swing.JButton();
        btnb26 = new javax.swing.JButton();
        btnb27 = new javax.swing.JButton();
        btnb28 = new javax.swing.JButton();
        btnb29 = new javax.swing.JButton();
        btnb30 = new javax.swing.JButton();
        btnb5 = new javax.swing.JButton();
        btnb15 = new javax.swing.JButton();
        btnb25 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Section A", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 153, 255))); // NOI18N

        btna1.setBackground(new java.awt.Color(255, 255, 255));
        btna1.setText("1");
        btna1.setName("btn1"); // NOI18N
        btna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna1ActionPerformed(evt);
            }
        });

        btna2.setBackground(new java.awt.Color(255, 255, 255));
        btna2.setText("2");
        btna2.setName("btn2"); // NOI18N
        btna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna2ActionPerformed(evt);
            }
        });

        btna3.setBackground(new java.awt.Color(255, 255, 255));
        btna3.setText("3");
        btna3.setName("btn3"); // NOI18N
        btna3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btna3MouseClicked(evt);
            }
        });

        btna4.setBackground(new java.awt.Color(255, 255, 255));
        btna4.setText("4");
        btna4.setName("btn4"); // NOI18N
        btna4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna4ActionPerformed(evt);
            }
        });

        btna5.setBackground(new java.awt.Color(204, 204, 255));
        btna5.setText("5");
        btna5.setName("btn5"); // NOI18N
        btna5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna5ActionPerformed(evt);
            }
        });

        btna6.setBackground(new java.awt.Color(204, 204, 255));
        btna6.setText("6");
        btna6.setName("btn6"); // NOI18N
        btna6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna6ActionPerformed(evt);
            }
        });

        btna7.setBackground(new java.awt.Color(255, 255, 255));
        btna7.setText("7");
        btna7.setName("btn7"); // NOI18N
        btna7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna7ActionPerformed(evt);
            }
        });

        btna8.setBackground(new java.awt.Color(255, 255, 255));
        btna8.setText("8");
        btna8.setName("btn8"); // NOI18N
        btna8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna8ActionPerformed(evt);
            }
        });

        btna9.setBackground(new java.awt.Color(255, 255, 255));
        btna9.setText("9");
        btna9.setName("btn9"); // NOI18N
        btna9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna9ActionPerformed(evt);
            }
        });

        btna10.setBackground(new java.awt.Color(255, 255, 255));
        btna10.setText("10");
        btna10.setName("btn10"); // NOI18N
        btna10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna10ActionPerformed(evt);
            }
        });

        btna12.setBackground(new java.awt.Color(255, 255, 255));
        btna12.setText("12");
        btna12.setName("btn12"); // NOI18N
        btna12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna12ActionPerformed(evt);
            }
        });

        btna13.setBackground(new java.awt.Color(255, 255, 255));
        btna13.setText("13");
        btna13.setName("btn13"); // NOI18N
        btna13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna13ActionPerformed(evt);
            }
        });

        btna14.setBackground(new java.awt.Color(255, 255, 255));
        btna14.setText("14");
        btna14.setName("btn14"); // NOI18N
        btna14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna14ActionPerformed(evt);
            }
        });

        btna15.setBackground(new java.awt.Color(204, 204, 255));
        btna15.setText("15");
        btna15.setName("btn15"); // NOI18N
        btna15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna15ActionPerformed(evt);
            }
        });

        btna16.setBackground(new java.awt.Color(204, 204, 255));
        btna16.setText("16");
        btna16.setName("btn16"); // NOI18N
        btna16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna16ActionPerformed(evt);
            }
        });

        btna17.setBackground(new java.awt.Color(255, 255, 255));
        btna17.setText("17");
        btna17.setName("btn17"); // NOI18N
        btna17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna17ActionPerformed(evt);
            }
        });

        btna18.setBackground(new java.awt.Color(255, 255, 255));
        btna18.setText("18");
        btna18.setName("btn18"); // NOI18N
        btna18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna18ActionPerformed(evt);
            }
        });

        btna19.setBackground(new java.awt.Color(255, 255, 255));
        btna19.setText("19");
        btna19.setName("btn19"); // NOI18N
        btna19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna19ActionPerformed(evt);
            }
        });

        btna20.setBackground(new java.awt.Color(255, 255, 255));
        btna20.setText("20");
        btna20.setName("btn20"); // NOI18N
        btna20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna20ActionPerformed(evt);
            }
        });

        btna22.setBackground(new java.awt.Color(255, 255, 255));
        btna22.setText("22");
        btna22.setName("btn22"); // NOI18N
        btna22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna22ActionPerformed(evt);
            }
        });

        btna23.setBackground(new java.awt.Color(255, 255, 255));
        btna23.setText("23");
        btna23.setName("btn23"); // NOI18N
        btna23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna23ActionPerformed(evt);
            }
        });

        btna24.setBackground(new java.awt.Color(255, 255, 255));
        btna24.setText("24");
        btna24.setName("btn24"); // NOI18N
        btna24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna24ActionPerformed(evt);
            }
        });

        btna25.setBackground(new java.awt.Color(204, 204, 255));
        btna25.setText("25");
        btna25.setName("btn25"); // NOI18N
        btna25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna25ActionPerformed(evt);
            }
        });

        btna26.setBackground(new java.awt.Color(204, 204, 255));
        btna26.setText("26");
        btna26.setName("btn26"); // NOI18N
        btna26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna26ActionPerformed(evt);
            }
        });

        btna27.setBackground(new java.awt.Color(255, 255, 255));
        btna27.setText("27");
        btna27.setName("btn27"); // NOI18N
        btna27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna27ActionPerformed(evt);
            }
        });

        btna28.setBackground(new java.awt.Color(255, 255, 255));
        btna28.setText("28");
        btna28.setName("btn28"); // NOI18N
        btna28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna28ActionPerformed(evt);
            }
        });

        btna29.setBackground(new java.awt.Color(255, 255, 255));
        btna29.setText("29");
        btna29.setName("btn29"); // NOI18N
        btna29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna29ActionPerformed(evt);
            }
        });

        btna30.setBackground(new java.awt.Color(255, 255, 255));
        btna30.setText("30");
        btna30.setName("btn30"); // NOI18N
        btna30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna30ActionPerformed(evt);
            }
        });

        btna21.setBackground(new java.awt.Color(255, 255, 255));
        btna21.setText("21");
        btna21.setName("btn21"); // NOI18N
        btna21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna21ActionPerformed(evt);
            }
        });

        btna11.setBackground(new java.awt.Color(255, 255, 255));
        btna11.setText("11");
        btna11.setName("btn11"); // NOI18N
        btna11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btna11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btna21, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna22, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna23, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna24, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btna4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btna5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btna15, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(btna25, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btna6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna26, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna27, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna28, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna29, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna30, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btna17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btna20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btna12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna20, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btna19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btna11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btna22, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna23, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna24, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna25, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna26, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna27, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna28, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna29, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna30, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btna21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Section B", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 153, 255))); // NOI18N

        btnb1.setBackground(new java.awt.Color(255, 255, 255));
        btnb1.setText("1");
        btnb1.setName("btn31"); // NOI18N
        btnb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb1ActionPerformed(evt);
            }
        });

        btnb2.setBackground(new java.awt.Color(255, 255, 255));
        btnb2.setText("2");
        btnb2.setName("btn32"); // NOI18N
        btnb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb2ActionPerformed(evt);
            }
        });

        btnb3.setBackground(new java.awt.Color(255, 255, 255));
        btnb3.setText("3");
        btnb3.setName("btn33"); // NOI18N
        btnb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb3ActionPerformed(evt);
            }
        });

        btnb4.setBackground(new java.awt.Color(255, 255, 255));
        btnb4.setText("4");
        btnb4.setName("btn34"); // NOI18N
        btnb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb4ActionPerformed(evt);
            }
        });

        btnb6.setBackground(new java.awt.Color(204, 204, 255));
        btnb6.setText("6");
        btnb6.setName("btn36"); // NOI18N
        btnb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb6ActionPerformed(evt);
            }
        });

        btnb7.setBackground(new java.awt.Color(255, 255, 255));
        btnb7.setText("7");
        btnb7.setName("btn37"); // NOI18N
        btnb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb7ActionPerformed(evt);
            }
        });

        btnb8.setBackground(new java.awt.Color(255, 255, 255));
        btnb8.setText("8");
        btnb8.setName("btn38"); // NOI18N
        btnb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb8ActionPerformed(evt);
            }
        });

        btnb9.setBackground(new java.awt.Color(255, 255, 255));
        btnb9.setText("9");
        btnb9.setName("btn39"); // NOI18N
        btnb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb9ActionPerformed(evt);
            }
        });

        btnb10.setBackground(new java.awt.Color(255, 255, 255));
        btnb10.setText("10");
        btnb10.setName("btn40"); // NOI18N
        btnb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb10ActionPerformed(evt);
            }
        });

        btnb11.setBackground(new java.awt.Color(255, 255, 255));
        btnb11.setText("11");
        btnb11.setName("btn41"); // NOI18N
        btnb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb11ActionPerformed(evt);
            }
        });

        btnb12.setBackground(new java.awt.Color(255, 255, 255));
        btnb12.setText("12");
        btnb12.setName("btn42"); // NOI18N
        btnb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb12ActionPerformed(evt);
            }
        });

        btnb13.setBackground(new java.awt.Color(255, 255, 255));
        btnb13.setText("13");
        btnb13.setName("btn43"); // NOI18N
        btnb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb13ActionPerformed(evt);
            }
        });

        btnb14.setBackground(new java.awt.Color(255, 255, 255));
        btnb14.setText("14");
        btnb14.setName("btn44"); // NOI18N
        btnb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb14ActionPerformed(evt);
            }
        });

        btnb16.setBackground(new java.awt.Color(204, 204, 255));
        btnb16.setText("16");
        btnb16.setName("btn46"); // NOI18N
        btnb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb16ActionPerformed(evt);
            }
        });

        btnb17.setBackground(new java.awt.Color(255, 255, 255));
        btnb17.setText("17");
        btnb17.setName("btn47"); // NOI18N
        btnb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb17ActionPerformed(evt);
            }
        });

        btnb18.setBackground(new java.awt.Color(255, 255, 255));
        btnb18.setText("18");
        btnb18.setName("btn48"); // NOI18N
        btnb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb18ActionPerformed(evt);
            }
        });

        btnb19.setBackground(new java.awt.Color(255, 255, 255));
        btnb19.setText("19");
        btnb19.setName("btn49"); // NOI18N
        btnb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb19ActionPerformed(evt);
            }
        });

        btnb20.setBackground(new java.awt.Color(255, 255, 255));
        btnb20.setText("20");
        btnb20.setName("btn50"); // NOI18N
        btnb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb20ActionPerformed(evt);
            }
        });

        btnb21.setBackground(new java.awt.Color(255, 255, 255));
        btnb21.setText("21");
        btnb21.setName("btn51"); // NOI18N
        btnb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb21ActionPerformed(evt);
            }
        });

        btnb22.setBackground(new java.awt.Color(255, 255, 255));
        btnb22.setText("22");
        btnb22.setName("btn52"); // NOI18N
        btnb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb22ActionPerformed(evt);
            }
        });

        btnb23.setBackground(new java.awt.Color(255, 255, 255));
        btnb23.setText("23");
        btnb23.setName("btn53"); // NOI18N
        btnb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb23ActionPerformed(evt);
            }
        });

        btnb24.setBackground(new java.awt.Color(255, 255, 255));
        btnb24.setText("24");
        btnb24.setName("btn54"); // NOI18N
        btnb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb24ActionPerformed(evt);
            }
        });

        btnb26.setBackground(new java.awt.Color(204, 204, 255));
        btnb26.setText("26");
        btnb26.setName("btn56"); // NOI18N
        btnb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb26ActionPerformed(evt);
            }
        });

        btnb27.setBackground(new java.awt.Color(255, 255, 255));
        btnb27.setText("27");
        btnb27.setName("btn57"); // NOI18N
        btnb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb27ActionPerformed(evt);
            }
        });

        btnb28.setBackground(new java.awt.Color(255, 255, 255));
        btnb28.setText("28");
        btnb28.setName("btn58"); // NOI18N
        btnb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb28ActionPerformed(evt);
            }
        });

        btnb29.setBackground(new java.awt.Color(255, 255, 255));
        btnb29.setText("29");
        btnb29.setName("btn59"); // NOI18N
        btnb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb29ActionPerformed(evt);
            }
        });

        btnb30.setBackground(new java.awt.Color(255, 255, 255));
        btnb30.setText("30");
        btnb30.setName("btn60"); // NOI18N
        btnb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb30ActionPerformed(evt);
            }
        });

        btnb5.setBackground(new java.awt.Color(204, 204, 255));
        btnb5.setText("5");
        btnb5.setName("btn35"); // NOI18N
        btnb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb5ActionPerformed(evt);
            }
        });

        btnb15.setBackground(new java.awt.Color(204, 204, 255));
        btnb15.setText("15");
        btnb15.setName("btn45"); // NOI18N
        btnb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb15ActionPerformed(evt);
            }
        });

        btnb25.setBackground(new java.awt.Color(204, 204, 255));
        btnb25.setText("25");
        btnb25.setName("btn55"); // NOI18N
        btnb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnb21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnb12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnb22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnb13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnb23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnb14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnb24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnb27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnb17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnb7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnb18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnb20, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnb14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnb15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnb13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnb19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnb21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb24, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnb26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnb25, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnb28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Section C", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jButton56.setBackground(new java.awt.Color(255, 255, 255));
        jButton56.setText("1");
        jButton56.setName("btn61"); // NOI18N

        jButton57.setBackground(new java.awt.Color(255, 255, 255));
        jButton57.setText("3");
        jButton57.setName("btn63"); // NOI18N

        jButton58.setBackground(new java.awt.Color(255, 255, 255));
        jButton58.setText("4");
        jButton58.setName("btn64"); // NOI18N

        jButton59.setBackground(new java.awt.Color(204, 204, 255));
        jButton59.setText("5");
        jButton59.setName("btn65"); // NOI18N

        jButton60.setBackground(new java.awt.Color(204, 204, 255));
        jButton60.setText("6");
        jButton60.setName("btn66"); // NOI18N

        jButton61.setBackground(new java.awt.Color(255, 255, 255));
        jButton61.setText("7");
        jButton61.setName("btn67"); // NOI18N

        jButton62.setBackground(new java.awt.Color(255, 255, 255));
        jButton62.setText("8");
        jButton62.setName("btn68"); // NOI18N

        jButton63.setBackground(new java.awt.Color(255, 255, 255));
        jButton63.setText("9");
        jButton63.setName("btn69"); // NOI18N

        jButton64.setBackground(new java.awt.Color(255, 255, 255));
        jButton64.setText("11");
        jButton64.setName("btn71"); // NOI18N

        jButton65.setBackground(new java.awt.Color(255, 255, 255));
        jButton65.setText("13");
        jButton65.setName("btn73"); // NOI18N

        jButton66.setBackground(new java.awt.Color(255, 255, 255));
        jButton66.setText("14");
        jButton66.setName("btn74"); // NOI18N

        jButton67.setBackground(new java.awt.Color(204, 204, 255));
        jButton67.setText("15");
        jButton67.setName("btn75"); // NOI18N

        jButton68.setBackground(new java.awt.Color(204, 204, 255));
        jButton68.setText("16");
        jButton68.setName("btn76"); // NOI18N

        jButton69.setBackground(new java.awt.Color(255, 255, 255));
        jButton69.setText("17");
        jButton69.setName("btn77"); // NOI18N

        jButton70.setBackground(new java.awt.Color(255, 255, 255));
        jButton70.setText("18");
        jButton70.setName("btn78"); // NOI18N

        jButton71.setBackground(new java.awt.Color(255, 255, 255));
        jButton71.setText("19");
        jButton71.setName("btn79"); // NOI18N

        jButton72.setBackground(new java.awt.Color(255, 255, 255));
        jButton72.setText("10");
        jButton72.setName("btn70"); // NOI18N

        jButton73.setBackground(new java.awt.Color(255, 255, 255));
        jButton73.setText("20");
        jButton73.setName("btn80"); // NOI18N

        jButton77.setBackground(new java.awt.Color(255, 255, 255));
        jButton77.setText("2");
        jButton77.setName("btn62"); // NOI18N

        jButton78.setBackground(new java.awt.Color(255, 255, 255));
        jButton78.setText("12");
        jButton78.setName("btn72"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton59, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jButton67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton63, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jButton62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton58, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton57, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton56, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton59, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton60, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton78, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton68, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private static int a14 = 1;
    private void btna14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna14ActionPerformed
        a14 = shorter(btna14, "14", a14, "A");
    }//GEN-LAST:event_btna14ActionPerformed
    private static int a1 = 1;
    private void btna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna1ActionPerformed
        a1 = shorter(btna1, "1", a1, "A");
    }//GEN-LAST:event_btna1ActionPerformed
    private static int a2 = 1;
    private void btna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna2ActionPerformed
        a2 = shorter(btna2, "2", a2, "A");
    }//GEN-LAST:event_btna2ActionPerformed
    private static int a3 = 1;
    private void btna3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btna3MouseClicked
        a3 = shorter(btna3, "3", a3, "A");
    }//GEN-LAST:event_btna3MouseClicked
    private static int a4 = 1;
    private void btna4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna4ActionPerformed
        a4 = shorter(btna4, "4", a4, "A");
    }//GEN-LAST:event_btna4ActionPerformed
    private static int a5 = 1;
    private void btna5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna5ActionPerformed
        a5 = shorter(btna5, "5", a5, "A");
    }//GEN-LAST:event_btna5ActionPerformed
    private static int a6 = 1;
    private void btna6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna6ActionPerformed
        a6 = shorter(btna6, "6", a6, "A");
    }//GEN-LAST:event_btna6ActionPerformed
    private static int a7 = 1;
    private void btna7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna7ActionPerformed
        a7 = shorter(btna7, "7", a7, "A");
    }//GEN-LAST:event_btna7ActionPerformed
    private static int a8 = 1;
    private void btna8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna8ActionPerformed
        a8 = shorter(btna8, "8", a8, "A");
    }//GEN-LAST:event_btna8ActionPerformed
    private static int a9 = 1;
    private void btna9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna9ActionPerformed
        a9 = shorter(btna9, "9", a9, "A");
    }//GEN-LAST:event_btna9ActionPerformed
    private static int a10 = 1;
    private void btna10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna10ActionPerformed
        a10 = shorter(btna10, "10", a10, "A");
    }//GEN-LAST:event_btna10ActionPerformed
    private static int a11 = 1;
    private void btna11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna11ActionPerformed
        a11 = shorter(btna11, "11", a11, "A");
    }//GEN-LAST:event_btna11ActionPerformed
    private static int a12 = 1;
    private void btna12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna12ActionPerformed
        a12 = shorter(btna12, "12", a12, "A");
    }//GEN-LAST:event_btna12ActionPerformed
    private static int a13 = 1;
    private void btna13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna13ActionPerformed
        a13 = shorter(btna13, "13", a13, "A");
    }//GEN-LAST:event_btna13ActionPerformed
    private static int a15 = 1;
    private void btna15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna15ActionPerformed
        a15 = shorter(btna15, "15", a15, "A");
    }//GEN-LAST:event_btna15ActionPerformed
    private static int a16 = 1;
    private void btna16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna16ActionPerformed
        a16 = shorter(btna16, "16", a16, "A");
    }//GEN-LAST:event_btna16ActionPerformed
    private static int a17 = 1;
    private void btna17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna17ActionPerformed
        a17 = shorter(btna17, "17", a17, "A");
    }//GEN-LAST:event_btna17ActionPerformed
    private static int a18 = 1;
    private void btna18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna18ActionPerformed
        a18 = shorter(btna18, "18", a18, "A");
    }//GEN-LAST:event_btna18ActionPerformed
    private static int a19 = 1;
    private void btna19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna19ActionPerformed
        a19 = shorter(btna19, "19", a19, "A");
    }//GEN-LAST:event_btna19ActionPerformed
    private static int a20 = 1;
    private void btna20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna20ActionPerformed
        a20 = shorter(btna20, "20", a20, "A");
    }//GEN-LAST:event_btna20ActionPerformed
    private static int a21 = 1;
    private void btna21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna21ActionPerformed
        a21 = shorter(btna21, "21", a21, "A");
    }//GEN-LAST:event_btna21ActionPerformed
    private static int a22 = 1;
    private void btna22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna22ActionPerformed
        a22 = shorter(btna22, "22", a22, "A");
    }//GEN-LAST:event_btna22ActionPerformed
    private static int a23 = 1;
    private void btna23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna23ActionPerformed
        a23 = shorter(btna23, "23", a23, "A");
    }//GEN-LAST:event_btna23ActionPerformed
    private static int a24 = 1;
    private void btna24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna24ActionPerformed
        a24 = shorter(btna24, "24", a24, "A");
    }//GEN-LAST:event_btna24ActionPerformed
    private static int a25 = 1;
    private void btna25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna25ActionPerformed
        a25 = shorter(btna25, "25", a25, "A");
    }//GEN-LAST:event_btna25ActionPerformed
    private static int a26 = 1;
    private void btna26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna26ActionPerformed
        a26 = shorter(btna26, "26", a26, "A");
    }//GEN-LAST:event_btna26ActionPerformed
    private static int a27 = 1;
    private void btna27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna27ActionPerformed
        a27 = shorter(btna27, "27", a27, "A");
    }//GEN-LAST:event_btna27ActionPerformed
    private static int a28 = 1;
    private void btna28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna28ActionPerformed
        a28 = shorter(btna28, "28", a28, "A");
    }//GEN-LAST:event_btna28ActionPerformed
    private static int a29 = 1;
    private void btna29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna29ActionPerformed
        a29 = shorter(btna29, "29", a29, "A");
    }//GEN-LAST:event_btna29ActionPerformed
    private static int a30 = 1;
    private void btna30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btna30ActionPerformed
        a30 = shorter(btna30, "30", a30, "A");
    }//GEN-LAST:event_btna30ActionPerformed
    private static int a31 = 1;
    private void btnb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb1ActionPerformed
        a31 = shorter(btnb1, "1", a31, "B");
    }//GEN-LAST:event_btnb1ActionPerformed
    private static int a32 = 1;
    private void btnb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb2ActionPerformed
        a32 = shorter(btnb2, "2", a32, "B");
    }//GEN-LAST:event_btnb2ActionPerformed
    private static int a33 = 1;
    private void btnb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb3ActionPerformed
        a33 = shorter(btnb3, "3", a33, "B");
    }//GEN-LAST:event_btnb3ActionPerformed
    private static int a34 = 1;
    private void btnb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb4ActionPerformed
        a34 = shorter(btnb4, "4", a34, "B");
    }//GEN-LAST:event_btnb4ActionPerformed
    private static int a35 = 1;
    private void btnb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb5ActionPerformed
        a35 = shorter(btnb5, "5", a35, "B");
    }//GEN-LAST:event_btnb5ActionPerformed
    private static int a36 = 1;
    private void btnb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb6ActionPerformed
        a36 = shorter(btnb6, "6", a36, "B");
    }//GEN-LAST:event_btnb6ActionPerformed
    private static int a37 = 1;
    private void btnb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb7ActionPerformed
        a37 = shorter(btnb7, "7", a37, "B");
    }//GEN-LAST:event_btnb7ActionPerformed
    private static int a38 = 1;
    private void btnb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb8ActionPerformed
        a38 = shorter(btnb8, "8", a38, "B");
    }//GEN-LAST:event_btnb8ActionPerformed
    private static int a39 = 1;
    private void btnb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb9ActionPerformed
        a39 = shorter(btnb9, "9", a39, "B");
    }//GEN-LAST:event_btnb9ActionPerformed
    private static int a40 = 1;
    private void btnb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb10ActionPerformed
        a40 = shorter(btnb10, "10", a40, "B");
    }//GEN-LAST:event_btnb10ActionPerformed
    private static int a41 = 1;
    private void btnb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb11ActionPerformed
        a41 = shorter(btnb11, "11", a41, "B");
    }//GEN-LAST:event_btnb11ActionPerformed
    private static int a42 = 1;
    private void btnb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb12ActionPerformed
        a42 = shorter(btnb12, "12", a42, "B");
    }//GEN-LAST:event_btnb12ActionPerformed
    private static int a43 = 1;
    private void btnb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb13ActionPerformed
        a43 = shorter(btnb13, "13", a43, "B");
    }//GEN-LAST:event_btnb13ActionPerformed
    private static int a44 = 1;
    private void btnb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb14ActionPerformed
        a44 = shorter(btnb14, "14", a44, "B");
    }//GEN-LAST:event_btnb14ActionPerformed
    private static int a45 = 1;
    private void btnb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb15ActionPerformed
        a45 = shorter(btnb15, "15", a45, "B");
    }//GEN-LAST:event_btnb15ActionPerformed
    private static int a46 = 1;
    private void btnb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb16ActionPerformed
        a46 = shorter(btnb16, "16", a46, "B");
    }//GEN-LAST:event_btnb16ActionPerformed
    private static int a47 = 1;
    private void btnb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb17ActionPerformed
        a47 = shorter(btnb17, "17", a47, "B");
    }//GEN-LAST:event_btnb17ActionPerformed
    private static int a48 = 1;
    private void btnb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb18ActionPerformed
        a48 = shorter(btnb18, "18", a48, "B");
    }//GEN-LAST:event_btnb18ActionPerformed
    private static int a49 = 1;
    private void btnb19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb19ActionPerformed
        a49 = shorter(btnb19, "19", a49, "B");
    }//GEN-LAST:event_btnb19ActionPerformed
    private static int a50 = 1;
    private void btnb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb20ActionPerformed
        a50 = shorter(btnb20, "20", a50, "B");
    }//GEN-LAST:event_btnb20ActionPerformed
    private static int a51 = 1;
    private void btnb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb21ActionPerformed
        a51 = shorter(btnb21, "21", a51, "B");
    }//GEN-LAST:event_btnb21ActionPerformed
    private static int a52 = 1;
    private void btnb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb22ActionPerformed
        a52 = shorter(btnb22, "22", a52, "B");
    }//GEN-LAST:event_btnb22ActionPerformed
    private static int a53 = 1;
    private void btnb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb23ActionPerformed
        a53 = shorter(btnb23, "23", a53, "B");
    }//GEN-LAST:event_btnb23ActionPerformed
    private static int a54 = 1;
    private void btnb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb24ActionPerformed
        a54 = shorter(btnb24, "24", a54, "B");
    }//GEN-LAST:event_btnb24ActionPerformed
    private static int a55 = 1;
    private void btnb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb25ActionPerformed
        a55 = shorter(btnb25, "25", a55, "B");
    }//GEN-LAST:event_btnb25ActionPerformed
    private static int a56 = 1;
    private void btnb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb26ActionPerformed
        a56 = shorter(btnb26, "26", a56, "B");
    }//GEN-LAST:event_btnb26ActionPerformed
    private static int a57 = 1;
    private void btnb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb27ActionPerformed
        a57 = shorter(btnb27, "27", a57, "B");
    }//GEN-LAST:event_btnb27ActionPerformed
    private static int a58 = 1;
    private void btnb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb28ActionPerformed
        a58 = shorter(btnb29, "28", a58, "B");
    }//GEN-LAST:event_btnb28ActionPerformed
    private static int a59 = 1;
    private void btnb29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb29ActionPerformed
        a59 = shorter(btnb29, "29", a59, "B");
    }//GEN-LAST:event_btnb29ActionPerformed
    private static int a60 = 1;
    private void btnb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb30ActionPerformed
        a60 = shorter(btnb30, "30", a60, "B");
    }//GEN-LAST:event_btnb30ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btna1;
    private javax.swing.JButton btna10;
    private javax.swing.JButton btna11;
    private javax.swing.JButton btna12;
    private javax.swing.JButton btna13;
    private javax.swing.JButton btna14;
    private javax.swing.JButton btna15;
    private javax.swing.JButton btna16;
    private javax.swing.JButton btna17;
    private javax.swing.JButton btna18;
    private javax.swing.JButton btna19;
    private javax.swing.JButton btna2;
    private javax.swing.JButton btna20;
    private javax.swing.JButton btna21;
    private javax.swing.JButton btna22;
    private javax.swing.JButton btna23;
    private javax.swing.JButton btna24;
    private javax.swing.JButton btna25;
    private javax.swing.JButton btna26;
    private javax.swing.JButton btna27;
    private javax.swing.JButton btna28;
    private javax.swing.JButton btna29;
    private javax.swing.JButton btna3;
    private javax.swing.JButton btna30;
    private javax.swing.JButton btna4;
    private javax.swing.JButton btna5;
    private javax.swing.JButton btna6;
    private javax.swing.JButton btna7;
    private javax.swing.JButton btna8;
    private javax.swing.JButton btna9;
    private javax.swing.JButton btnb1;
    private javax.swing.JButton btnb10;
    private javax.swing.JButton btnb11;
    private javax.swing.JButton btnb12;
    private javax.swing.JButton btnb13;
    private javax.swing.JButton btnb14;
    private javax.swing.JButton btnb15;
    private javax.swing.JButton btnb16;
    private javax.swing.JButton btnb17;
    private javax.swing.JButton btnb18;
    private javax.swing.JButton btnb19;
    private javax.swing.JButton btnb2;
    private javax.swing.JButton btnb20;
    private javax.swing.JButton btnb21;
    private javax.swing.JButton btnb22;
    private javax.swing.JButton btnb23;
    private javax.swing.JButton btnb24;
    private javax.swing.JButton btnb25;
    private javax.swing.JButton btnb26;
    private javax.swing.JButton btnb27;
    private javax.swing.JButton btnb28;
    private javax.swing.JButton btnb29;
    private javax.swing.JButton btnb3;
    private javax.swing.JButton btnb30;
    private javax.swing.JButton btnb4;
    private javax.swing.JButton btnb5;
    private javax.swing.JButton btnb6;
    private javax.swing.JButton btnb7;
    private javax.swing.JButton btnb8;
    private javax.swing.JButton btnb9;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String message) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateLabel(String messege) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateLbl(JLabel lbl, String text) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void incCID(String cid) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateButton(JButton btn, String text) throws RemoteException {
        if (text.equals("A")) {
            System.out.println(text);
            for (Component c : jPanel2.getComponents()) {
                if (!(c instanceof JButton)) {
                    continue;
                }
                if (c.getName().equals(btn.getName())) {
                    JButton newButton = (JButton) c;
                    newButton.setText(text);
                }
            }
        } else if (text.equals("B")) {
            for (Component c : jPanel3.getComponents()) {
                if (!(c instanceof JButton)) {
                    continue;
                }
                if (c.getName().equals(btn.getName())) {
                    JButton newButton = (JButton) c;
                    newButton.setText(text);
                }
            }
        } else if (text.equals("C")) {
            for (Component c : jPanel4.getComponents()) {
                if (!(c instanceof JButton)) {
                    continue;
                }
                if (c.getName().equals(btn.getName())) {
                    JButton newButton = (JButton) c;
                    newButton.setText(text);
                }
            }

        }
    }

    public int shorter(JButton btn, String txt, int times, String letter) {
        String psslbl;
        int j = times;
        if (j % 2 != 0) {
            psslbl = letter;
            j++;
        } else {
            psslbl = txt;
            j++;
        }

        try {
            System.out.println("Working");
            BookedController bcc = ServerConnector.getServerConnector().getBookedController();
            bcc.changeButtons(btn, psslbl);

        } catch (RemoteException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestingWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return j;
    }

    @Override
    public void AdjustMID(String mid) throws RemoteException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
